In [1]:
library(tidyverse)


── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1 
✔ readr   2.1.2      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()


In [2]:
HTRU2 <- read_csv("HTRU2/HTRU_2.csv")


Rows: 17897 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (9): 140.5625, 55.68378214, -0.234571412, -0.699648398, 3.199832776, 19....

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.


In [3]:
names(HTRU2) <- c("Mean_IP", "SD_IP", "EK_IP", "SKW_IP", "Mean_DMSNR", "SD_DMSNR", "EK_DMSNR", "SKW_DMSNR", "Class")


In [4]:
class(HTRU2) # Specific to General


[1] "spec_tbl_df" "tbl_df"      "tbl"         "data.frame"

In [5]:
head(HTRU2)


Mean_IP   SD_IP    EK_IP       SKW_IP     Mean_DMSNR SD_DMSNR  EK_DMSNR 
1 102.50781 58.88243  0.46531815 -0.5150879 1.6772575  14.860146 10.576487
2 103.01562 39.34165  0.32332837  1.0511644 3.1212375  21.744669  7.735822
3 136.75000 57.17845 -0.06841464 -0.6362384 3.6429766  20.959280  6.896499
4  88.72656 40.67223  0.60086608  1.1234917 1.1789298  11.468720 14.269573
5  93.57031 46.69811  0.53190485  0.4167211 1.6362876  14.545074 10.621748
6 119.48438 48.76506  0.03146022 -0.1121676 0.9991639   9.279612 19.206230
  SKW_DMSNR Class
1 127.39358 0    
2  63.17191 0    
3  53.59366 0    
4 252.56731 0    
5 131.39400 0    
6 479.75657 0

# Vector


In [6]:
Lengths_A <- c(52, 51, 60, 64, 69, 74, 78, 84, 86, 96, 104, 112, 118, 125, 132, 135)


In [7]:
mode(Lengths_A)


[1] "numeric"

In [8]:
class(Lengths_A)


[1] "numeric"

In [9]:
Lengths_A[1]


[1] 52

In [10]:
Lengths_A + rep(1, 16) # Repeat +1 16 times and apply to each index


[1]  53  52  61  65  70  75  79  85  87  97 105 113 119 126 133 136

In [11]:
1:9


[1] 1 2 3 4 5 6 7 8 9

In [12]:
mode(1:9)


[1] "numeric"

In [13]:
class(1:9)


[1] "integer"

In [14]:
one_to_ten <- 1:10


In [15]:
print(one_to_ten)


 [1]  1  2  3  4  5  6  7  8  9 10


In [16]:
class(one_to_ten)


[1] "integer"

**integer** requires less storage space compared to **numeric** (think of it as a double)

Putting a "L" after the number turns it into an integer


In [17]:
one_to_ten + c(1, 2)


[1]  2  4  4  6  6  8  8 10 10 12

In [18]:
one_to_ten


[1]  1  2  3  4  5  6  7  8  9 10

# Functions and Methods


In [19]:
sum(c(3, 5, NA)) # NA stands for Not Available, it's like a missing value


[1] NA

In [20]:
sum(c(3, 5, NA), na.rm = T) # na.rm as name suggests it removes missing value


[1] 8

In [21]:
sum(one_to_ten, c(1, 2, 3))


[1] 61

In [22]:
args(mean)


function (x, ...) 
NULL

In [23]:
args(mean.default)


function (x, trim = 0, na.rm = FALSE, ...) 
NULL

In [24]:
args(sum)


function (..., na.rm = FALSE) 
NULL

In [25]:
methods(mean)


[1] mean.Date        mean.default     mean.difftime    mean.integer64* 
[5] mean.POSIXct     mean.POSIXlt     mean.quosure*    mean.vctrs_vctr*
see '?methods' for accessing help and source code

In [26]:
# ?methods # Opens up a help window


# More on Vector


### Atomic Vector

- Integer
- Double
- Logical
- Character
- Complex
- Raw

### Recursive Vector

- List


In [27]:
is.atomic(one_to_ten)


[1] TRUE

In [28]:
# help("is.vector")


In [29]:
# help("is.atomic")


# R-objects

R lang has various R-objects, which are the following.

- Vector
- List
- Factor
- Matrix
- Array
- DataFrame


# Matrix


In [30]:
matrix3x3 <- matrix(1L:9L, nrow = 3, ncol = 3)


In [31]:
print(matrix3x3)


     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [32]:
class(matrix3x3) # Left to Right: Specific to General


[1] "matrix" "array"

In [33]:
# help(class)


In [34]:
# help(matrix)


In [35]:
mode(matrix3x3)


[1] "numeric"

In [36]:
class(matrix3x3[1])


[1] "integer"

In [37]:
attributes(matrix3x3)


$dim
[1] 3 3

In [38]:
dim(matrix3x3)


[1] 3 3

In [39]:
print(matrix3x3)


     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [40]:
matrix3x3[2, 1] # First row then col


[1] 2

In [41]:
matrix3x3[3]


[1] 3

In [42]:
matrix3x3 * matrix3x3


[,1] [,2] [,3]
[1,] 1    16   49  
[2,] 4    25   64  
[3,] 9    36   81

In [43]:
matrix3x3 * t(matrix3x3) # t() is transpose


[,1] [,2] [,3]
[1,]  1    8   21  
[2,]  8   25   48  
[3,] 21   48   81

In [44]:
matrix3x3 %*% matrix3x3 # %*% means matrix multiplication


[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

# Lists


In [45]:
U1 <- c(203, 204)
U2 <- c(323, 324, 447)
U3 <- c(208, 427, 423, 523, 545)


In [46]:
mymcgill_stats <- list(U1, U2, U3, "Statistics Major")


In [47]:
print(mymcgill_stats)


[[1]]
[1] 203 204

[[2]]
[1] 323 324 447

[[3]]
[1] 208 427 423 523 545

[[4]]
[1] "Statistics Major"



In [48]:
mymcgill_stats <- list(U1 = U1, U2 = U2, U3 = U3, Major = "Statistics Major")


In [49]:
print(mymcgill_stats)


$U1
[1] 203 204

$U2
[1] 323 324 447

$U3
[1] 208 427 423 523 545

$Major
[1] "Statistics Major"



In [50]:
mymcgill_stats[["U2"]] # Only get the content


[1] 323 324 447

In [51]:
mymcgill_stats["U2"] # Get the content + the name


$U2
[1] 323 324 447

In [52]:
mymcgill_stats$U2


[1] 323 324 447

In [53]:
mymcgill_stats


$U1
[1] 203 204

$U2
[1] 323 324 447

$U3
[1] 208 427 423 523 545

$Major
[1] "Statistics Major"

In [54]:
mymcgill_stats[c(1, 2)]


$U1
[1] 203 204

$U2
[1] 323 324 447

In [55]:
mymcgill_stats[[c(1, 2)]] # IMPORTANT: Recursive indexing 1st of outer, 2nd of inner


[1] 204

In [56]:
mymcgill_stats[[1]][[2]]


[1] 204

In [57]:
mymcgill_stats[c("U1", "U2")]


$U1
[1] 203 204

$U2
[1] 323 324 447

# Data Frame vs Tibble


In [58]:
htru2_df <- read.csv("HTRU2/HTRU_2.csv", header = FALSE) # read.csv gives us a data.frame


In [59]:
class(htru2_df)


[1] "data.frame"

In [60]:
head(htru2_df)


V1        V2       V3          V4         V5       V6       V7       
1 140.56250 55.68378 -0.23457141 -0.6996484 3.199833 19.11043  7.975532
2 102.50781 58.88243  0.46531815 -0.5150879 1.677258 14.86015 10.576487
3 103.01562 39.34165  0.32332837  1.0511644 3.121237 21.74467  7.735822
4 136.75000 57.17845 -0.06841464 -0.6362384 3.642977 20.95928  6.896499
5  88.72656 40.67223  0.60086608  1.1234917 1.178930 11.46872 14.269573
6  93.57031 46.69811  0.53190485  0.4167211 1.636288 14.54507 10.621748
  V8        V9
1  74.24222 0 
2 127.39358 0 
3  63.17191 0 
4  53.59366 0 
5 252.56731 0 
6 131.39400 0

In [61]:
htru2_tbl <- read_csv("HTRU2/HTRU_2.csv", col_names = FALSE) # read_csv gives us a tibble


Rows: 17898 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (9): X1, X2, X3, X4, X5, X6, X7, X8, X9

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.


In [62]:
head(as.data.frame(htru2_tbl))


X1        X2       X3          X4         X5       X6       X7       
1 140.56250 55.68378 -0.23457141 -0.6996484 3.199833 19.11043  7.975532
2 102.50781 58.88243  0.46531815 -0.5150879 1.677258 14.86015 10.576487
3 103.01562 39.34165  0.32332837  1.0511644 3.121237 21.74467  7.735822
4 136.75000 57.17845 -0.06841464 -0.6362384 3.642977 20.95928  6.896499
5  88.72656 40.67223  0.60086608  1.1234917 1.178930 11.46872 14.269573
6  93.57031 46.69811  0.53190485  0.4167211 1.636288 14.54507 10.621748
  X8        X9
1  74.24222 0 
2 127.39358 0 
3  63.17191 0 
4  53.59366 0 
5 252.56731 0 
6 131.39400 0

In [63]:
mymcgill_stats_tbl <- tibble(
    Courses = list(U1 = U1, U2 = U2, U3 = U3),
    Year = c("U1", "U2", "U3"),
    Major = rep("Statistics Major", 3)
)

mymcgill_stats_tbl


Courses                 Year Major           
1 203, 204                U1   Statistics Major
2 323, 324, 447           U2   Statistics Major
3 208, 427, 423, 523, 545 U3   Statistics Major

In [64]:
names(attributes(htru2_tbl))


[1] "row.names" "names"     "spec"      "problems"  "class"

In [65]:
attributes(htru2_tbl)$names


[1] "X1" "X2" "X3" "X4" "X5" "X6" "X7" "X8" "X9"

In [66]:
print(htru2_tbl)


# A tibble: 17,898 × 9
      X1    X2      X3     X4    X5    X6    X7    X8    X9
   <dbl> <dbl>   <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
 1 141.   55.7 -0.235  -0.700 3.20  19.1   7.98  74.2     0
 2 103.   58.9  0.465  -0.515 1.68  14.9  10.6  127.      0
 3 103.   39.3  0.323   1.05  3.12  21.7   7.74  63.2     0
 4 137.   57.2 -0.0684 -0.636 3.64  21.0   6.90  53.6     0
 5  88.7  40.7  0.601   1.12  1.18  11.5  14.3  253.      0
 6  93.6  46.7  0.532   0.417 1.64  14.5  10.6  131.      0
 7 119.   48.8  0.0315 -0.112 0.999  9.28 19.2  480.      0
 8 130.   39.8 -0.158   0.390 1.22  14.4  13.5  198.      0
 9 107.   52.6  0.453   0.170 2.33  14.5   9.00 108.      0
10 107.   39.5  0.466   1.16  4.08  25.0   7.40  57.8     0
# … with 17,888 more rows


In [67]:
names(htru2_tbl) <- c("Mean_IP", "SD_IP", "EK_IP", "SKW_IP", "Mean_DMSNR", "SD_DMSNR", "EK_DMSNR", "SKW_DMSNR", "Class")
print(htru2_tbl)


# A tibble: 17,898 × 9
   Mean_IP SD_IP   EK_IP SKW_IP Mean_DMSNR SD_DMSNR EK_DMSNR SKW_DMSNR Class
     <dbl> <dbl>   <dbl>  <dbl>      <dbl>    <dbl>    <dbl>     <dbl> <dbl>
 1   141.   55.7 -0.235  -0.700      3.20     19.1      7.98      74.2     0
 2   103.   58.9  0.465  -0.515      1.68     14.9     10.6      127.      0
 3   103.   39.3  0.323   1.05       3.12     21.7      7.74      63.2     0
 4   137.   57.2 -0.0684 -0.636      3.64     21.0      6.90      53.6     0
 5    88.7  40.7  0.601   1.12       1.18     11.5     14.3      253.      0
 6    93.6  46.7  0.532   0.417      1.64     14.5     10.6      131.      0
 7   119.   48.8  0.0315 -0.112      0.999     9.28    19.2      480.      0
 8   130.   39.8 -0.158   0.390      1.22     14.4     13.5      198.      0
 9   107.   52.6  0.453   0.170      2.33     14.5      9.00     108.      0
10   107.   39.5  0.466   1.16       4.08     25.0      7.40      57.8     0
# … with 17,888 more rows


# Subsetting


In [68]:
Lengths_A # Subsetting vector


[1]  52  51  60  64  69  74  78  84  86  96 104 112 118 125 132 135

In [69]:
Lengths_A[c(1, 2, 5)] # subsetting by index


[1] 52 51 69

In [70]:
Lengths_A > 100


[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE
[13]  TRUE  TRUE  TRUE  TRUE

In [71]:
Lengths_A[Lengths_A > 100]


[1] 104 112 118 125 132 135

In [72]:
mymcgill_stats # Subsetting list


$U1
[1] 203 204

$U2
[1] 323 324 447

$U3
[1] 208 427 423 523 545

$Major
[1] "Statistics Major"

In [73]:
mymcgill_stats[c(1, 3)]


$U1
[1] 203 204

$U3
[1] 208 427 423 523 545

In [74]:
lapply(mymcgill_stats, length)


$U1
[1] 2

$U2
[1] 3

$U3
[1] 5

$Major
[1] 1

In [75]:
lapply(mymcgill_stats, length) < 4


U1    U2    U3 Major 
 TRUE  TRUE FALSE  TRUE

In [76]:
mymcgill_stats[lapply(mymcgill_stats, length) < 4]


$U1
[1] 203 204

$U2
[1] 323 324 447

$Major
[1] "Statistics Major"

In [77]:
matrix3x4 <- matrix(1:12, ncol = 4, nrow = 3)


In [78]:
matrix3x4


[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [79]:
matrix3x4 <- matrix(c(1:12), ncol = 4, nrow = 3, byrow = T)


In [80]:
matrix3x4


[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [81]:
matrix3x4[3, 1]


[1] 9

In [82]:
matrix3x4[, c(1:3)] # Subsetting[<Row>,<Col>]


[,1] [,2] [,3]
[1,] 1     2    3  
[2,] 5     6    7  
[3,] 9    10   11

In [83]:
matrix3x4[c(2, 3), c(3:4)] # Subsetting[<Row>,<Col>]


[,1] [,2]
[1,]  7    8  
[2,] 11   12

In [84]:
matrix3x4[c(FALSE, TRUE, TRUE), c(FALSE, FALSE, TRUE, TRUE)]


[,1] [,2]
[1,]  7    8  
[2,] 11   12

In [85]:
matrix3x4 %% 2 == 0


[,1]  [,2] [,3]  [,4]
[1,] FALSE TRUE FALSE TRUE
[2,] FALSE TRUE FALSE TRUE
[3,] FALSE TRUE FALSE TRUE

In [86]:
matrix3x4[matrix3x4 %% 2 == 0] # It prints from cols to cols, not from rows to rows


[1]  2  6 10  4  8 12

In [87]:
matrix3x4


[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [88]:
names(htru2_df) <- names(htru2_tbl)


In [89]:
head(htru2_df) # Subsetting data.frame


Mean_IP   SD_IP    EK_IP       SKW_IP     Mean_DMSNR SD_DMSNR EK_DMSNR 
1 140.56250 55.68378 -0.23457141 -0.6996484 3.199833   19.11043  7.975532
2 102.50781 58.88243  0.46531815 -0.5150879 1.677258   14.86015 10.576487
3 103.01562 39.34165  0.32332837  1.0511644 3.121237   21.74467  7.735822
4 136.75000 57.17845 -0.06841464 -0.6362384 3.642977   20.95928  6.896499
5  88.72656 40.67223  0.60086608  1.1234917 1.178930   11.46872 14.269573
6  93.57031 46.69811  0.53190485  0.4167211 1.636288   14.54507 10.621748
  SKW_DMSNR Class
1  74.24222 0    
2 127.39358 0    
3  63.17191 0    
4  53.59366 0    
5 252.56731 0    
6 131.39400 0

In [90]:
htru2_df[c(1, 2), c(3, 4)]


EK_IP      SKW_IP    
1 -0.2345714 -0.6996484
2  0.4653182 -0.5150879

In [91]:
htru2_df_MIP14 <- htru2_df[htru2_df$Mean_IP > 140, 1:3]
dim(htru2_df_MIP14)


[1] 1276    3

In [92]:
head(htru2_df[htru2_df$Mean_IP > 140, c("Mean_IP", "SD_IP", "Class")])


Mean_IP  SD_IP    Class
1  140.5625 55.68378 0    
11 142.0781 45.28807 0    
34 142.0547 53.87316 0    
37 147.8359 53.62264 0    
59 141.9688 50.47090 0    
67 143.0859 49.92197 0

In [93]:
htru2_df_MIP14_sub <- subset(htru2_df, Mean_IP > 140) # Subsetting df with subset function


In [94]:
head(htru2_df_MIP14_sub)


Mean_IP  SD_IP    EK_IP      SKW_IP     Mean_DMSNR SD_DMSNR EK_DMSNR
1  140.5625 55.68378 -0.2345714 -0.6996484 3.199833   19.11043 7.975532
11 142.0781 45.28807 -0.3203284  0.2839525 5.376254   29.00990 6.076266
34 142.0547 53.87316 -0.4707727 -0.1259464 4.423077   27.08351 6.681658
37 147.8359 53.62264 -0.1310796 -0.2888512 2.692308   17.08088 8.849178
59 141.9688 50.47090  0.2449745 -0.3426647 2.823579   16.23819 8.207744
67 143.0859 49.92197 -0.1575612 -0.1533327 3.563545   21.28808 7.337117
   SKW_DMSNR Class
1  74.24222  0    
11 37.83139  0    
34 45.94403  0    
37 92.20175  0    
59 85.53258  0    
67 59.16844  0

In [95]:
head(htru2_tbl)


Mean_IP   SD_IP    EK_IP       SKW_IP     Mean_DMSNR SD_DMSNR EK_DMSNR 
1 140.56250 55.68378 -0.23457141 -0.6996484 3.199833   19.11043  7.975532
2 102.50781 58.88243  0.46531815 -0.5150879 1.677258   14.86015 10.576487
3 103.01562 39.34165  0.32332837  1.0511644 3.121237   21.74467  7.735822
4 136.75000 57.17845 -0.06841464 -0.6362384 3.642977   20.95928  6.896499
5  88.72656 40.67223  0.60086608  1.1234917 1.178930   11.46872 14.269573
6  93.57031 46.69811  0.53190485  0.4167211 1.636288   14.54507 10.621748
  SKW_DMSNR Class
1  74.24222 0    
2 127.39358 0    
3  63.17191 0    
4  53.59366 0    
5 252.56731 0    
6 131.39400 0

In [96]:
htru2_tbl[1:3, c(1, 5, 9)] # Subsetting tibble


Mean_IP  Mean_DMSNR Class
1 140.5625 3.199833   0    
2 102.5078 1.677258   0    
3 103.0156 3.121237   0

In [97]:
head(select(htru2_tbl, Mean_IP, Mean_DMSNR, Class))


Mean_IP   Mean_DMSNR Class
1 140.56250 3.199833   0    
2 102.50781 1.677258   0    
3 103.01562 3.121237   0    
4 136.75000 3.642977   0    
5  88.72656 1.178930   0    
6  93.57031 1.636288   0

In [98]:
slice(htru2_tbl, 1:3)


Mean_IP  SD_IP    EK_IP      SKW_IP     Mean_DMSNR SD_DMSNR EK_DMSNR 
1 140.5625 55.68378 -0.2345714 -0.6996484 3.199833   19.11043  7.975532
2 102.5078 58.88243  0.4653182 -0.5150879 1.677258   14.86015 10.576487
3 103.0156 39.34165  0.3233284  1.0511644 3.121237   21.74467  7.735822
  SKW_DMSNR Class
1  74.24222 0    
2 127.39358 0    
3  63.17191 0

In [99]:
slice(select(htru2_tbl, Mean_IP, Class), c(1:3))


Mean_IP  Class
1 140.5625 0    
2 102.5078 0    
3 103.0156 0

In [100]:
slice(select(filter(htru2_tbl, Mean_IP > 140), Mean_IP, SD_IP), 1:5)


Mean_IP  SD_IP   
1 140.5625 55.68378
2 142.0781 45.28807
3 142.0547 53.87316
4 147.8359 53.62264
5 141.9688 50.47090

In [101]:
filter(select(slice(htru2_tbl, 1:5), Mean_IP, SD_IP), Mean_IP > 140)


Mean_IP  SD_IP   
1 140.5625 55.68378

# Packages


In [102]:
search()


[1] ".GlobalEnv"        "package:forcats"   "package:stringr"  
 [4] "package:dplyr"     "package:purrr"     "package:readr"    
 [7] "package:tidyr"     "package:tibble"    "package:ggplot2"  
[10] "package:tidyverse" "jupyter:irkernel"  "package:stats"    
[13] "package:graphics"  "package:grDevices" "package:utils"    
[16] "package:datasets"  "package:methods"   "Autoloads"        
[19] "package:base"

In [103]:
Lengths_B <- c(51, 53.5, 56, 66, 68, 72.5, 79, 80, 81, 91, 96.8, 101, 110)
Lengths_C <- c(52.5, 49.5, 60, 65, 67, 74, 78, 79, 83, 90)


In [104]:
Dates_A <- c(
    "2009-05-02", "2009-05-11", "2009-07-07", "2009-09-09",
    "2009-11-16", "2010-02-16", "2010-05-03", "2010-11-09",
    "2011-05-04", "2012-05-03", "2013-05-18", "2014-07-30",
    "2015-09-30", "2016-06-08", "2017-08-21", "2018-09-19"
)


In [105]:
mode(Dates_A)


[1] "character"

In [106]:
class(Dates_A)


[1] "character"

In [107]:
Dates_A <- as.Date(Dates_A)


In [108]:
mode(Dates_A)


[1] "numeric"

In [109]:
class(Dates_A)


[1] "Date"

In [110]:
head(Dates_A)


[1] "2009-05-02" "2009-05-11" "2009-07-07" "2009-09-09" "2009-11-16"
[6] "2010-02-16"

In [111]:
head(as.numeric(Dates_A)) # Total amount of days since 1/1/1970


[1] 14366 14375 14432 14496 14564 14656

In [112]:
Dates_B <- as.Date(c(
    "2012-08-02", "2012-08-15", "2012-10-31", "2012-12-06",
    "2013-02-18", "2013-05-13", "2013-09-05", "2014-02-17",
    "2014-07-30", "2015-09-30", "2016-08-04", "2017-08-21",
    "2018-09-19"
))
Dates_C <- as.Date(c(
    "2016-02-04", "2016-02-18", "2016-04-11", "2016-06-08",
    "2016-08-04", "2016-11-17", "2017-03-02", "2017-08-21",
    "2018-02-20", "2019-02-13"
))


In [113]:
kids_heights_df <- data.frame(
    Kid = c(
        rep("A", length(Lengths_A)), rep("B", length(Lengths_B)), rep("C", length(Lengths_C))
    ),
    Heights = c(Lengths_A, Lengths_B, Lengths_C),
    Dates = c(Dates_A, Dates_B, Dates_C)
)
head(kids_heights_df)


Kid Heights Dates     
1 A   52      2009-05-02
2 A   51      2009-05-11
3 A   60      2009-07-07
4 A   64      2009-09-09
5 A   69      2009-11-16
6 A   74      2010-02-16

In [114]:
kids_heights_tbl <- tibble(
    Kid = c(rep("A", length(Lengths_A)), rep("B", length(Lengths_B)), rep("C", length(Lengths_C))),
    Heights = c(Lengths_A, Lengths_B, Lengths_C),
    Dates = c(Dates_A, Dates_B, Dates_C)
)
head(kids_heights_tbl)


Kid Heights Dates     
1 A   52      2009-05-02
2 A   51      2009-05-11
3 A   60      2009-07-07
4 A   64      2009-09-09
5 A   69      2009-11-16
6 A   74      2010-02-16

In [115]:
length(Lengths_A) + length(Lengths_B) + length(Lengths_C)
length(Dates_A) + length(Dates_B) + length(Dates_C)


[1] 39

[1] 39

In [116]:
str(kids_heights_tbl)


tibble [39 × 3] (S3: tbl_df/tbl/data.frame)
 $ Kid    : chr [1:39] "A" "A" "A" "A" ...
 $ Heights: num [1:39] 52 51 60 64 69 74 78 84 86 96 ...
 $ Dates  : Date[1:39], format: "2009-05-02" "2009-05-11" ...


In [117]:
kids_heights_tlb_grp <- group_by(kids_heights_tbl, Kid)


In [118]:
str(kids_heights_tlb_grp)


grouped_df [39 × 3] (S3: grouped_df/tbl_df/tbl/data.frame)
 $ Kid    : chr [1:39] "A" "A" "A" "A" ...
 $ Heights: num [1:39] 52 51 60 64 69 74 78 84 86 96 ...
 $ Dates  : Date[1:39], format: "2009-05-02" "2009-05-11" ...
 - attr(*, "groups")= tibble [3 × 2] (S3: tbl_df/tbl/data.frame)
  ..$ Kid  : chr [1:3] "A" "B" "C"
  ..$ .rows: list<int> [1:3] 
  .. ..$ : int [1:16] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..$ : int [1:13] 17 18 19 20 21 22 23 24 25 26 ...
  .. ..$ : int [1:10] 30 31 32 33 34 35 36 37 38 39
  .. ..@ ptype: int(0) 
  ..- attr(*, ".drop")= logi TRUE


In [119]:
# Adding a column with mutate
kids_heights_tlb_grp <- mutate(kids_heights_tlb_grp, Birth = min(Dates), Age = Dates - min(Dates))


In [120]:
head(kids_heights_tlb_grp)


Kid Heights Dates      Birth      Age     
1 A   52      2009-05-02 2009-05-02   0 days
2 A   51      2009-05-11 2009-05-02   9 days
3 A   60      2009-07-07 2009-05-02  66 days
4 A   64      2009-09-09 2009-05-02 130 days
5 A   69      2009-11-16 2009-05-02 198 days
6 A   74      2010-02-16 2009-05-02 290 days

In [121]:
# magrittr package has a forward pipe operator: %>%
# Making the code more readable

kids_heights_tbl_grp <- kids_heights_tbl %>%
    group_by(Kid) %>%
    mutate(
        Birth = min(Dates),
        Age = Dates - min(Dates)
    ) %>%
    head(10)

str(kids_heights_tbl_grp)


grouped_df [10 × 5] (S3: grouped_df/tbl_df/tbl/data.frame)
 $ Kid    : chr [1:10] "A" "A" "A" "A" ...
 $ Heights: num [1:10] 52 51 60 64 69 74 78 84 86 96
 $ Dates  : Date[1:10], format: "2009-05-02" "2009-05-11" ...
 $ Birth  : Date[1:10], format: "2009-05-02" "2009-05-02" ...
 $ Age    : 'difftime' num [1:10] 0 9 66 130 ...
  ..- attr(*, "units")= chr "days"
 - attr(*, "groups")= tibble [1 × 2] (S3: tbl_df/tbl/data.frame)
  ..$ Kid  : chr "A"
  ..$ .rows: list<int> [1:1] 
  .. ..$ : int [1:10] 1 2 3 4 5 6 7 8 9 10
  .. ..@ ptype: int(0) 
  ..- attr(*, ".drop")= logi TRUE
